name: CI - Build + Security Gates

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or commit to run (e.g. main or refs/heads/feature/foo)'
        required: false
        default: 'main'
      env:
        description: 'Environment'
        required: false
        default: 'dev'
  push:
    branches:
      - main
      - develop
      - 'release/*'
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read
  packages: write
  id-token: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/devsecops-sample
  IMAGE_TAG: ${{ github.sha }}

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # If workflow_dispatch provides `inputs.ref`, use it; otherwise fall back to the event ref.
          ref: ${{ github.event.inputs.ref || github.ref }}


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (for local lint/build tasks)
        run: npm ci

      - name: Run Semgrep (static code analysis)
        uses: returntocorp/semgrep-action@v1
        with:
          config: 'p/ci'     # public baseline; replace with './semgrep-rules' to use custom rules
        # semgrep will exit non-zero if rules have severity 'ERROR' or are configured to fail

      - name: Build image (local tag)
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: false
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Debug Trivy action resolution (network & tag)
        run: |
          echo "== runner info =="
          uname -a
          echo "GITHUB_RUNNER_SCOPE=$GITHUB_RUNNER_SCOPE"
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_REF=$GITHUB_REF"
          echo

          echo "== Can reach GitHub API for release tag =="
          curl -sS -I https://api.github.com/repos/aquasecurity/trivy-action/releases/tags/v0.33.1 || true
          echo

          echo "== Can fetch raw action file =="
          curl -sS -I https://raw.githubusercontent.com/aquasecurity/trivy-action/v0.33.1/action.yml || true
          echo

          echo "== Can resolve releases list (for sanity) =="
          curl -sS -I https://api.github.com/repos/aquasecurity/trivy-action/releases || true
          echo

          echo "== DNS resolution test for raw.githubusercontent.com =="
          getent hosts raw.githubusercontent.com || nslookup raw.githubusercontent.com || true
          echo

          echo "== show effective environment (redact secrets) =="
          env | sed -n '1,200p'


      - name: Trivy - filesystem scan (repository)
        id: trivy-fs
        uses: aquasecurity/trivy-action@v0.33.1
        with:
          scan-type: fs
          scan-ref: '.'
          format: json
          output: trivy-fs-report.json
          severity: CRITICAL,HIGH
          ignore-unfixed: false

      - name: Upload trivy-fs report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs-report
          path: trivy-fs-report.json

      - name: Trivy - image scan (fail on HIGH/CRITICAL)
        id: trivy-image
        uses: aquasecurity/trivy-action@v0.33.1
        with:
          scan-type: image
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: json
          output: trivy-image-report.json
          severity: CRITICAL,HIGH
          exit-code: 1           # exit 1 if any HIGH/CRITICAL found

      - name: Upload trivy-image report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-image-report
          path: trivy-image-report.json

      # Optional Snyk step (comment out if not using Snyk)
      #- name: Snyk test (container + project)
      #  uses: snyk/actions/docker@master
      #  with:
      #    command: test
      #    args: --severity-threshold=high
      #  env:
      #    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Push only on main and only after all gates passed
      - name: Log in to GHCR
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GHCR (main only)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
